// <auto-generated />
namespace ASPNetFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VusalCVv10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VusalCVv10));
        
        string IMigrationMetadata.Id
        {
            get { return "201905291420092_VusalCV v 1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
