// <auto-generated />
namespace ASPNetFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class VusalCVv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VusalCVv2));
        
        string IMigrationMetadata.Id
        {
            get { return "201906011340431_VusalCV.v.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
